version: '3.4'

services:
  deliveggiedb:
    container_name: deliveggiedb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  deliveggieapp.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - deliveggiedb
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro