version: '3.4'

services:
  deliveggiedb:
    image: mongo
  deliveggieapp.apigateway:
    image: ${DOCKER_REGISTRY-}deliveggieappapigateway
    build:
      context: .
      dockerfile: DeliVeggieApp.APIGateway/Dockerfile
volumes:
  mongo_data:
